### ISSUE TITLE
Install instructions in README.md

### ISSUE THREAD

**Issue by saidaibrg** [iRove108/markups#6]
Hi Alex. In your README file, the section "Install from source" is a bit unclear. Could you please clarify what `pip install .` means? I tried running it in the Terminal before testing out a new color for highlights, and got the error `Directory '.' isn't installable. Neither 'setup.py' nor 'pyproject.toml' found.` 
Thanks!

**Comment by iRove108** [comment]
Hi Saida,
Thanks for pointing this out—I'll work to improve the setup instructions a bit. Are you in the root project directory? e.g.
```
git clone https://github.com/iRove108/markups.git
cd markups
pip install .
```

**Comment by saidaibrg** [comment]
Thank you for clarifying on this Alex! It worked this time.
